# Generated by Django 6.0.3 on 2026-03-31 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TramiteLicencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula_numero', models.CharField(max_length=10, unique=True)),
                ('archivo_cedula', models.FileField(blank=True, null=True, upload_to='cedulas/')),
                ('paso_actual', models.IntegerField(default=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
