# Generated by Django 6.0.3 on 2026-04-25 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_licencias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='tramitelicencia',
            name='archivo_psico',
            field=models.FileField(blank=True, null=True, upload_to='psicosensometrico/'),
        ),
        migrations.AddField(
            model_name='tramitelicencia',
            name='archivo_sangre',
            field=models.FileField(blank=True, null=True, upload_to='sangre/'),
        ),
        migrations.AddField(
            model_name='tramitelicencia',
            name='pago_completado',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AfluenciaHistorica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(help_text='0=Lunes, 6=Domingo')),
                ('hora', models.IntegerField()),
                ('espera_promedio_minutos', models.IntegerField()),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='gestion_licencias.sucursal')),
            ],
        ),
    ]
