# Generated by Django 6.0.5 on 2026-05-10 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_licencias', '0004_zonas_iniciales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramitelicencia',
            name='zona',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tramites', to='gestion_licencias.zona'),
            preserve_default=False,
        ),
    ]
