# Generated by Django 6.0.5 on 2026-05-10 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_licencias', '0005_alter_tramitelicencia_zona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramitelicencia',
            name='zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tramites', to='gestion_licencias.zona'),
        ),
    ]
