# Generated by Django 6.0.5 on 2026-06-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_licencias', '0006_alter_tramitelicencia_zona'),
    ]

    operations = [
        migrations.AddField(
            model_name='zona',
            name='latitud',
            field=models.FloatField(default=-0.1807),
        ),
        migrations.AddField(
            model_name='zona',
            name='longitud',
            field=models.FloatField(default=-78.4678),
        ),
    ]
